server:
  port: 8080

spring:
  datasource:
    username: root
    password: zj123456
    url: jdbc:mysql://localhost:3306/mysql?uDriverseUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
   redisson:
   config: classpath:redisson.yaml
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.hyssop.framework.entity


project:
  env: dev